### ISSUE TITLE
Mobile-Buy-SDK deprecations

### ISSUE THREAD

**Issue by AntonoffEvgeniy** [rubygarage/shopapp-shopify-ios#19]
- WARN  | xcodebuild:  ShopApp_Shopify/Shopify/API/ShopifyAPI.swift:1213:19: warning: 'src(alias:)' is deprecated: Previously an image had a single `src` field. This could either return the original image
    - WARN  | xcodebuild:  ShopApp_Shopify/Shopify/API/Adapters/ShopifyImageAdapter.swift:20:26: warning: 'src' is deprecated: Previously an image had a single `src` field. This could either return the original image

**Comment by radyslavkrechet** [comment]
It was fixed in version 1.0.5
