### ISSUE TITLE
Can't find ShopApp/Data/DI/DataAssembly.swift

### ISSUE THREAD

**Issue by asikand** [rubygarage/shopapp-shopify-ios#24]
I can't find the file that I am told to edit in the Readme. Has the setup instructions changed for this app? In addition, what is the difference between 'API Key' and 'Admin API Key'? I'm assuming that API Key is the _Storefront API Key_.

**Comment by plzen** [comment]
Hello @asikand,

This repository is Shopify provider for ShopApp - you can find all install instructions by this link https://github.com/rubygarage/shopapp-ios.

_API Key_ - it's Storefront API key, you are right.
_Admin API Key_ is separate credentials which used for fetching countries and states from your shop.
