### ISSUE TITLE
No default

### ISSUE THREAD

**Issue by lewishalliday1** [rubygarage/shopapp-shopify-ios#26]
I've followed all the instructions but just seem to be getting a 'Cannot find default' on all pages. 

I can see my categories but I can't see any products within that. The products have api visibility but nothing seems to load. Is there anything specific I need to do?

**Comment by lewishalliday1** [comment]
Never mind - started working. Didn't do anything specific must have just taken a bit of time.

**Comment by Tyfoo16** [comment]
But I am still encountering this issue. I have waited 20 mins +. Any solution for this or any way I can debug?

**Comment by LiatheHNaj** [comment]
i am having the same issue
